[tool.black]
line-length = 109
#include='/sample/'
#exclude=''
#check=true
#preview=true
verbose=true
include='/sample/'
#exclude='/sample/dd.py|/sample/test.py'
#force-exclude='/sample/dd.py|/sample/test.py'